# This is a TOML document. Boom.

# 监听地址
ListenAddress = ":15555"

#主页地址
HomeUrl = "/h"

#跳转的远程端口
ForwardPort = ":55555"

#静态文件,根目录的文件夹名字: yaaw ==> /yaaw
StaticFS = ["d","yaaw","aria"]


#BasicAuth 访问的用户名和密码
#http://admin:admin321@127.0.0.1:55555/yaaw/
#http://guest:guest@127.0.0.1:55555/yaaw/
[Accounts]
#用户名admin，密码admin321,密码必须小写
admin="admin321"

#guest="guest"

