# This is a TOML document. Boom.

# 监听地址
ListenAddress = ":15555"

#主页地址
HomeUrl = "/h"

#跳转的远程端口
ForwardPort = ":55555"

#静态文件,根目录的文件夹名字: yaaw ==> /yaaw
StaticFS = ["d","yaaw","aria"]

